### ISSUE TITLE
What software license is this project?

### ISSUE THREAD

**Issue by yooper** [kiwicommerce/magento2-admin-activity#14]
What open source license does this project use? It is not explicitly stated anywhere

**Comment by lenlorijn** [comment]
I would like to know the same thing.

**Comment by lenlorijn** [comment]
@yooper I found it by following the link in the file headers. It's OSL-3.0. https://kiwicommerce.co.uk/magento2-extension-license/

**Comment by yooper** [comment]
Thanks
