### ISSUE TITLE
Magento 2.4.0 error in backend 

### ISSUE THREAD

**Issue by karpa** [kiwicommerce/magento2-admin-activity#16]
After installing the module to magento 2.4.0 with command "composer require  kiwicommerce/module-admin-activity" i got the following error after trying to login to backend.

The test was on a clean instalation of magento 2.4.0
<pre>
1 exception(s):
Exception #0 (Exception): Notice: Trying to access array offset on value of type bool in /vendor/kiwicommerce/module-admin-activity/Model/Processor.php on line 447

Exception #0 (Exception): Notice: Trying to access array offset on value of type bool in /vendor/kiwicommerce/module-admin-activity/Model/Processor.php on line 447
#1 KiwiCommerce\AdminActivity\Model\Processor->_initLog() called at [vendor/kiwicommerce/module-admin-activity/Model/Processor.php:629]
#2 KiwiCommerce\AdminActivity\Model\Processor->addPageVisitLog() called at [vendor/kiwicommerce/module-admin-activity/Plugin/App/Action.php:57]
#3 KiwiCommerce\AdminActivity\Plugin\App\Action->beforeDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:121]
#4 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#5 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins() called at [generated/code/Magento/Backend/Controller/Adminhtml/Index/Index/Interceptor.php:39]
#6 Magento\Backend\Controller\Adminhtml\Index\Index\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#7 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#8 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#9 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#10 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#11 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#12 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#13 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#14 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#15 Magento\Framework\App\Bootstrap->run() called at [index.php:39]
</pre>

**Comment by paugnu** [comment]
This PR fixes the issue:
https://github.com/kiwicommerce/magento2-admin-activity/pull/15

**Comment by kiwi-commerce** [comment]
Hello,

Thank you for your report.
We have merged changes of PR #15 and it will be released on the next upcoming version.

Thank you.
