### ISSUE TITLE
Revert Issue

### ISSUE THREAD

**Issue by hammockvienna** [kiwicommerce/magento2-admin-activity#7]
Hi

when i try to revert a change it get
"A technical problem with the server created an error. Try again to continue what you were doing. If the problem persists, try again later."

PHP7.2
Magento 2.3.2

In the log files i dont see any exception. Any idea?

**Comment by kiwi-commerce** [comment]
Hello @hammockvienna ,

We couldn't find exact steps to reproduce this issue so we are closing this issue.
Feel free to reopen it by providing steps to reproduce the issue.

Thank you.
